### ISSUE TITLE
map error with len in python 3

### ISSUE THREAD

**Issue by celiasmith** [arvoelke/nengolib#118]
This code works ok in python 2, but breaks in python 3

```
import numpy as np
import nengo
import nengolib

dt = 0.001  # simulation dt
tau = 0.01  # recurrent synapse used for principle 3

freq = 2 * np.pi / 0.5   # oscillator frequency in radians
A = 0 # define the dynamics; here an integrator

ABCD = (A, [1], np.eye(1), [0])

# Apply discrete principle 3 to the linear system (A, B, C, D)
msys = nengolib.synapses.ss2sim(map(np.asarray, ABCD), nengo.Lowpass(tau), dt=dt)
```
There are some differences in how ```map``` is treated across the versions.

**Comment by arvoelke** [comment]
I don't consider this a bug in nengolib. This is a bug in the code that is using nengolib. Specifically, a `linear_system_like` has to be one of [these types](https://arvoelke.github.io/nengolib-docs/types.html#linear_system_like), which doesn't include iterables.

The person who wrote this code (me) shouldn't have published it as an example.

Work-around:

```
msys = nengolib.synapses.ss2sim(tuple(map(np.asarray, ABCD)), nengo.Lowpass(tau), dt=dt)
```
