### ISSUE TITLE
ImportError with Scipy v1.3.0

### ISSUE THREAD

**Issue by psipeter** [arvoelke/nengolib#180]
Looks like the `pade` function has moved from `scipy.misc` to `scipy.interpolate` in Scipy v.1.3.0

**Comment by arvoelke** [comment]
That's what I get for ignoring deprecation warnings. Thanks for the report.

**Comment by ikajic** [comment]
I made a [PR](https://github.com/ikajic/nengolib/pull/1) in the wrong repository (:-1:) more than a week ago to resolve this.. now it's in the right place (#182), though by now you probably have dealt with it yourself. Sorry about this.

**Comment by arvoelke** [comment]
Fixed by #182. Thanks @ikajic!
