### ISSUE TITLE
`with_metaclass` import from nengo.utils.compat not working

### ISSUE THREAD

**Issue by ikajic** [arvoelke/nengolib#183]
The import of `with_metaclass` from `nengo.utils.compat` is invalid due to deprecation of `nengo.utils.compat`:
https://github.com/arvoelke/nengolib/blob/c52923973e964b1e0b7cdc1d28d878ba6e8e42fe/nengolib/signal/system.py#L10

See [this commit](https://github.com/nengo/nengo/commit/9422a62a8faf43352f667762966cf1da279d9f5d#diff-65b08fafb2509cf98b5405a3eb21768e) for more details.

**Comment by arvoelke** [comment]
Nengolib does not support `nengo>=3.0.0` (i.e., the development branch) as documented in `setup.py` and [the documentation](https://arvoelke.github.io/nengolib-docs/). Closing as this is superceded by #184.
